version: '3'

services:
  ollama:
    image: ollama/ollama:0.11.4
    container_name: ollama
    volumes:
      - ../huggingface_models:/workspace/huggingface_models
      - ../ollama_models:/workspace/ollama_models
    working_dir: /workspace
    tty: true
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
