version: '3'

services:
  ollama:
    image: ollama/ollama:0.6.7
    container_name: ollama
    volumes:
      - ../models:/workspace/models
    working_dir: /workspace
    tty: true
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
